version: '3.8'

services:
  django:
    image:
      django-app: latest
    build:
      context: .
      dockerfile: dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "1999:8000"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DATABASE_URL=postgres://postgres:postgres@db:5432/voca_in
    volumes:
      - .:/app
    secrets:
      - db_password
      - aes_key
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  celery:
    image:
      celery-app: latest
    build:
      context: .
      dockerfile: dockerfile
    command: celery -A voca_backend worker --loglevel=info --logfile=logs/celery.log
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DATABASE_URL=postgres://postgres:postgres@db:5432/voca_in
    volumes:
      - .:/app
    secrets:
      - db_password
      - aes_key
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  rabbitmq:
    image: "rabbitmq:3-management"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: 
      postgres: 13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=voca_in
      - POSTGRES_USER=postgres
    secrets:
      - db_password
      - aes_key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
  nltk_data:

secrets:
  db_password:
    external: true
  aes_key:
    external: true

networks:
  default:
    driver: overlay
